FIXED_HEADER_FMT = '!4BL'
FIXED_HEADER_LEN = 8
PROTOCOL_VERSION = 0
RESERVED_BYTE = 0

MESSAGE_ERROR = 0
MESSAGE_PING = 1
MESSAGE_INFERENCE = 2

MESSAGE_REQUEST = 0
MESSAGE_RESPONSE = 1

ERROR_PROTOCOL = 0
ERROR_SUBTYPE = 1
ERROR_METHOD = 2
ERROR_MEMORY = 3
ERROR_INTERNAL = 5